name: Build and Push Docker Image

on:
  push:
  workflow_dispatch:

env:
  CONTAINER_APP_NAME: ca-cca-demo-eastus-001
  RESOURCE_GROUP: rg-cca-demo-eastus-001
  PORT: 8000
  INGRESS: external
  FULL_IMAGE_NAME: ${{ inputs.ACR }}/${{ inputs.IMAGE_NAME }}:${{ inputs.TAG }}

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v2
        with:
          login-server: crcustomercompliantalertdemoeastus001.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        working-directory: ./src
        run: |
          az acr build --registry crcustomercompliantalertdemoeastus001 \
                         --image customercompliantalert:${{ github.sha }} .

      - name: Deploy to Azure Container Apps
        working-directory: ./src
        uses: azure/container-apps-deploy-action@v1
        with:
          containerAppName: ${{ env.CONTAINER_APP_NAME }}
          resourceGroup: ${{ env.RESOURCE_GROUP }}
          imageToDeploy: customercompliantalert:${{ github.sha }}
          targetPort: ${{ env.PORT }}
          ingress: ${{ env.INGRESS }}